<a href="https://colab.research.google.com/github/Aryannchoudhary/Machine_learning_and_Deep_Learning_Models/blob/main/iris_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [ ]:
df=sns.load_dataset("iris")

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=df.drop(['species'],axis=1)
y=df['species']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn=KNeighborsClassifier(n_neighbors=5)

In [ ]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
model_knn.score(X_test,y_test)

1.0

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm=SVC()

In [ ]:
model_svm.fit(X_train,y_train)

SVC()

In [ ]:
model_svm.score(X_test,y_test)

1.0

In [ ]:
# now let use the grid search cv

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier=GridSearchCV(model_svm,{
    'C':[1,10,20],
    'kernel':['rbf','linear'],
},cv=5,return_train_score=False)

In [ ]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [ ]:
Result=pd.DataFrame(classifier.cv_results_)
Result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004563,0.000547,0.003046,0.000172,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,5
1,0.003838,0.000135,0.002781,0.000069,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003723,0.000292,0.002723,0.000197,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003736,0.000027,0.002797,0.000070,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.003797,0.000107,0.002735,0.000186,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.003774,0.000333,0.002978,0.000480,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,5

In [ ]:
result=Result[['param_C','param_kernel','mean_test_score']]
result.sort_values(by='mean_test_score',ascending=False)

   param_C param_kernel  mean_test_score
1        1       linear         0.980000
2       10          rbf         0.980000
4       20          rbf         0.980000
3       10       linear         0.973333
0        1          rbf         0.966667
5       20       linear         0.966667

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r=RandomizedSearchCV(model_svm,{
    'C':[1,10,20],
    'kernel':['rbf','linear'],
},n_iter=4,cv=5,return_train_score=False)

In [ ]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=4,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
result_r=pd.DataFrame(classifier_r.cv_results_)
result_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10       linear         0.973333
1        1          rbf         0.966667
2       20          rbf         0.980000
3       10          rbf         0.980000